services:
  # Web service
  - type: web
    name: nlp-cv-video-adapter
    env: python
    buildCommand: pip install -r requirements.txt && python download_nltk_data.py
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-queue
          property: connectionString

  # Background worker
  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt && python download_nltk_data.py
    startCommand: celery -A celery_worker.celery worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-queue
          property: connectionString

  # Redis instance
  - type: redis
    name: redis-queue
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # or starter
